### PR TITLE
fixes issue #20 bug that caused wrong character to ground distance measurement

### LINKED ISSUE #20: [Bug]: raycast on CollisionsManager reporting wrong height to character's LocalController
### Describe the bug

When importing vertically stacked structures from GLB models in MML documents, the `currentHeight` property on the character's `LocalController.ts` reports the wrong value, causing the `getTargetAnimation` to return a falsely-positive `AnimationState.air` state, hence, making the character appear with a falling animation while it's walking down the structure.

This type of structure triggers the bug:
Screenshot 2023-08-12 at 15 17 33

Observable bug behavior:
Screenshot 2023-08-12 at 15 30 42

Expected/correct behavior:
Screenshot 2023-08-12 at 15 31 37

Cause of the bug:
The `three-mesh-bvh` `raycast` method [invoked from the `raycastFirstDistance`](https://github.com/mml-io/3d-web-experience/blob/a69741642cf2efeea38799aa15d06aaa3a886c72/packages/3d-web-client-core/src/collisions/CollisionsManager.ts#L48) method on our `CollisionsManager` class does not return the hits array in the consistent and predictable order we expect, making the `0` index value not to be the expected one (the closest hit point from the ray's origin).

How to solve:
Replacing the `raycast` method from `three-mesh-bvh` with the `raycastFirst` method from the same package guarantees that only the ray hit against the closest mesh in the ray direction will be returned, hence, we get the correct `currentHeight` property on the `LocalController` class allowing us to properly identify the right animation state according to the `characterOnGround`, `currentHeight` and `characterVelocity.y` values.

### Expected behavior

The `currentHeight` property's value on the `LocalController` class should always be the distance from the ray origin (character's object pivot) to the closest mesh in the `vectorDown` ray direction.

### How to reproduce the bug

By importing any structure similar to the one in the provided screenshot (ideally flights of stairs that can be climbed down) and trying to walk down after passing the second flight of stairs. 

### Link to the code that reproduces this bug

https://github.com/mml-io/3d-web-experience/blob/a69741642cf2efeea38799aa15d06aaa3a886c72/packages/3d-web-client-core/src/collisions/CollisionsManager.ts#L48

### Extra details

Fix already implemented and tested will be pushed in my next PR.

### PR DESCRIPTION
**Pull request by TheCodeTherapy**
Resolves #20 

This PR fixes the [issue](https://github.com/mml-io/3d-web-experience/issues/20) causing wrong values on the character to ground distance measurement due to the use of an improper `raycast` method on the `CollisionsManager` class.

**What kind of change does your PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Tests
- [ ] Other, please describe:

**Does your PR fulfill the following requirements?**

- [X] The title references the corresponding issue # (if relevant)

### CODE REVIEW

File: packages/3d-web-client-core/src/collisions/CollisionsManager.ts [hunk 1]
```diff
@@ -45,10 +45,10 @@ export class CollisionsManager {
   public raycastFirstDistance(ray: Ray): number | null {
     let minimumDistance: number = Infinity;
```
Comment (MarcusLongmuir) [inline packages/3d-web-client-core/src/collisions/CollisionsManager.ts:46]: Just noticed that we don't actually return `null` if there isn't a distance. This could be type `number | null` and be set to `null`.

Comment (TheCodeTherapy) [reply packages/3d-web-client-core/src/collisions/CollisionsManager.ts]: Fixed in the [latest commit](https://github.com/mml-io/3d-web-experience/pull/24/commits/5666755670e32931fd5e041ffae592d384c22f40)

**Review by MarcusLongmuir — APPROVED** [review]
